name: Testing bug

on: [push]

jobs:
  bug-test:
    runs-on: ubuntu-latest

    steps:
      - name: clone-application
        uses: actions/checkout@v3

      - name: my-shell
        run: |
          mkdir myArtifact
          ls -la
          cd myArtifact

      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: myArtifact

      - name: my-shell
        run: |
          ls -la

      - name: artifact download
        uses: actions/download-artifact@v1
        with:
          name: myArtifact/test.txt
          path: myArtifact
