name: Testing bug

on: [push]

jobs:
  bug-test:
    runs-on: ubuntu-latest

    steps:
      - name: clone-application
        uses: actions/checkout@v3

      - name: my-shell
        run: |
          mkdir myArtifact
          ls -la
          cp test.txt myArtifact/tst.txt
          cd myArtifact

      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: myArtifact/tst.txt
          path: .

      - name: my-shell
        run: |
          cd myArtifact
          ls -la

      - name: artifact download
        uses: actions/download-artifact@v1
        with:
          name: tst.txt
          path: myArtifact
